using System.Text.Json;
using WWOnline.Patcher.Patches;

namespace WWOnline.Patcher.Config;

/// <summary>
/// Configuration for the patcher pipeline. Resolves paths to game files and devkitPPC tools.
/// </summary>
public class PatcherConfig
{
    public const string ConfigFileName = "config.json";
    public const string ExampleConfigFileName = "config.example.json";

    /// <summary>Output: the patched game directory (sys/, files/). Overwritten by every build.</summary>
    public string GamePath { get; set; } = string.Empty;
    public string DevKitPpcPath { get; set; } = string.Empty;

    /// <summary>
    /// Extracted vanilla game (sys/main.dol, sys/bi2.bin, files/RELS.arc) the build starts from.
    /// Nintendo's files are never committed; when unset, falls back to GameMod/vanilla/ (gitignored).
    /// </summary>
    public string VanillaGamePath { get; set; } = string.Empty;

    /// <summary>The GameMod/ folder: C/ASM sources, include/, build/ output, config.json.</summary>
    public string GameModPath { get; set; } = string.Empty;

    /// <summary>
    /// Optional patch ids to apply (GameMod/src/patches/optional/&lt;id&gt;.asm). Null = the
    /// catalogue defaults (each patch's <c>@default</c>); empty = none.
    /// </summary>
    public IReadOnlyList<string>? OptionalPatches { get; set; }

    /// <summary>
    /// Where generated build output goes (the REL + objects, link_draw_hook.asm, patch_diffs/,
    /// custom_symbols.txt). Null = the legacy in-tree locations under GameMod/ (gitignored), which
    /// the full build and dev-test use. --build-patchdata points it at a temp folder so building
    /// release PatchData never touches the source tree.
    /// </summary>
    public string? BuildOutputPath { get; set; }

    public string SysPath => Path.Combine(GamePath, "sys");
    public string FilesPath => Path.Combine(GamePath, "files");
    public string MainDolPath => Path.Combine(SysPath, "main.dol");
    public string RelsArcPath => Path.Combine(FilesPath, "RELS.arc");
    public string Bi2Path => Path.Combine(SysPath, "bi2.bin");

    // Vanilla reference files (read-only inputs)
    public string ResolvedVanillaGamePath => string.IsNullOrWhiteSpace(VanillaGamePath)
        ? Path.Combine(GameModPath, "vanilla")
        : VanillaGamePath;
    public string VanillaMainDolPath => Path.Combine(ResolvedVanillaGamePath, "sys", "main.dol");
    public string VanillaRelsArcPath => Path.Combine(ResolvedVanillaGamePath, "files", "RELS.arc");
    public string VanillaBi2Path => Path.Combine(ResolvedVanillaGamePath, "sys", "bi2.bin");

    // Source paths
    public string IncludePath => Path.Combine(GameModPath, "include");
    public string PuppetLinkSrcPath => Path.Combine(GameModPath, "src", "puppet_link");
    public string PatchesSrcPath => Path.Combine(GameModPath, "src", "patches");
    public string BuildPath => BuildOutputPath == null ? Path.Combine(GameModPath, "build") : Path.Combine(BuildOutputPath, "build");

    // devkitPPC
    public string DevKitBinPath => Path.Combine(DevKitPpcPath, "bin");
    public string LinkerScriptPath => Path.Combine(IncludePath, "ww_linker.ld");
    public string AsmMacrosPath => Path.Combine(PatchesSrcPath, "asm_macros.asm");
    public string FreeSpaceOffsetsPath => Path.Combine(PatchesSrcPath, "free_space_start_offsets.txt");
    public string PatchDiffsPath => Path.Combine(BuildOutputPath ?? PatchesSrcPath, "patch_diffs");

    /// <summary>link_draw_hook.asm, generated by HookAsmGenerator and assembled as a required patch.</summary>
    public string GeneratedHookAsmPath => Path.Combine(BuildOutputPath ?? PatchesSrcPath, HookAsmFileName);
    public const string HookAsmFileName = "link_draw_hook.asm";

    /// <summary>Symbols the assembled patches defined (debugging aid, not an input).</summary>
    public string CustomSymbolsPath => Path.Combine(BuildOutputPath ?? PatchesSrcPath, "custom_symbols.txt");
    public string OptionalPatchesSrcPath => Path.Combine(PatchesSrcPath, OptionalPatchCatalog.DirectoryName);
    public string OptionalPatchDiffsPath => PatchPlan.OptionalDiffsDirectory(PatchDiffsPath);
    public string PuppetSharedHeaderPath => Path.Combine(PuppetLinkSrcPath, "puppet_shared.h");

    /// <summary>GameMod/assets: files optional patches copy into the game (replace-file edits).</summary>
    public string AssetsPath => Path.Combine(GameModPath, "assets");

    public OptionalPatchCatalog LoadOptionalPatchCatalog() => OptionalPatchCatalog.Load(OptionalPatchesSrcPath);

    /// <summary>The selection this build applies; throws on unknown ids or conflicting patches.</summary>
    public PatchSelection ResolveOptionalPatches() => PatchPlan.ResolveStrict(LoadOptionalPatchCatalog(), OptionalPatches);

    /// <summary>
    /// Returns the full path to a devkitPPC binary, with .exe on Windows.
    /// </summary>
    public string GetToolPath(string toolName)
    {
        var name = OperatingSystem.IsWindows() ? toolName + ".exe" : toolName;
        return Path.Combine(DevKitBinPath, name);
    }

    /// <summary>
    /// Load config from GameMod/config.json (machine-specific, gitignored; see config.example.json).
    /// </summary>
    public static PatcherConfig LoadFromConfigJson(string gameModPath)
    {
        var configPath = Path.Combine(gameModPath, ConfigFileName);
        if (!File.Exists(configPath))
            throw new FileNotFoundException(
                $"{ConfigFileName} not found at {configPath}. Copy " +
                $"{Path.Combine(gameModPath, ExampleConfigFileName)} to {ConfigFileName} and fill in " +
                "game_path, vanilla_game_path and devkitppc_path.");

        var json = File.ReadAllText(configPath);
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        var gamePath = root.GetProperty("game_path").GetString() ?? string.Empty;
        var vanillaGamePath = root.TryGetProperty("vanilla_game_path", out var vp)
            ? vp.GetString() ?? string.Empty
            : string.Empty;
        var devkitPath = root.TryGetProperty("devkitppc_path", out var dp)
            ? dp.GetString() ?? string.Empty
            : string.Empty;

        if (string.IsNullOrEmpty(devkitPath))
            devkitPath = DefaultDevKitPpcPath();

        return new PatcherConfig
        {
            GamePath = gamePath,
            VanillaGamePath = vanillaGamePath,
            DevKitPpcPath = devkitPath,
            GameModPath = gameModPath,
        };
    }

    /// <summary>
    /// devkitPPC when nothing names it: the DEVKITPPC environment variable if it is an existing
    /// folder, else C:\devkitPro\devkitPPC (Windows) or /opt/devkitpro/devkitPPC. (The Windows
    /// installer sets DEVKITPPC to an MSYS path like /opt/devkitpro/devkitPPC, which doesn't exist
    /// as a Windows path, so it falls through to the default there.)
    /// </summary>
    public static string DefaultDevKitPpcPath()
    {
        var env = Environment.GetEnvironmentVariable("DEVKITPPC");
        if (!string.IsNullOrWhiteSpace(env) && Directory.Exists(env)) return env;
        return OperatingSystem.IsWindows() ? @"C:\devkitPro\devkitPPC" : "/opt/devkitpro/devkitPPC";
    }

    /// <summary>
    /// Create config with explicit paths (for testing or programmatic use).
    /// </summary>
    public static PatcherConfig Create(string gamePath, string devKitPpcPath, string gameModPath,
        string vanillaGamePath = "")
    {
        return new PatcherConfig
        {
            GamePath = gamePath,
            VanillaGamePath = vanillaGamePath,
            DevKitPpcPath = devKitPpcPath,
            GameModPath = gameModPath,
        };
    }

    /// <summary>
    /// Parse a free_space_start_offsets.txt file into a dictionary of path → address.
    /// Shared by AsmParser and DolPatcher.
    /// </summary>
    public static Dictionary<string, uint> LoadFreeSpaceOffsets(string filePath)
    {
        var offsets = new Dictionary<string, uint>();
        if (!File.Exists(filePath)) return offsets;

        foreach (var rawLine in File.ReadAllLines(filePath))
        {
            var line = rawLine.Trim();
            if (string.IsNullOrEmpty(line) || line.StartsWith('#')) continue;
            var colonIdx = line.IndexOf(':');
            if (colonIdx < 0) continue;

            var path = line[..colonIdx].Trim();
            var offsetStr = line[(colonIdx + 1)..].Trim();
            offsets[path] = ParseHexOrDecimal(offsetStr);
        }
        return offsets;
    }

    /// <summary>
    /// Parse a string as hex (with 0x prefix) or decimal.
    /// </summary>
    public static uint ParseHexOrDecimal(string s) =>
        s.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
            ? Convert.ToUInt32(s[2..], 16)
            : Convert.ToUInt32(s);

    public void Validate()
    {
        if (!Directory.Exists(GamePath))
            throw new DirectoryNotFoundException($"Game path not found: {GamePath}");
        if (!File.Exists(VanillaMainDolPath))
            throw new FileNotFoundException(
                $"Vanilla main.dol not found at {VanillaMainDolPath}. Set vanilla_game_path in " +
                $"{Path.Combine(GameModPath, ConfigFileName)} to an extracted vanilla game (sys/, files/).");
        ValidateToolchain();
    }

    /// <summary>devkitPPC is installed where <see cref="DevKitPpcPath"/> says.</summary>
    public void ValidateToolchain()
    {
        if (!Directory.Exists(DevKitBinPath))
            throw new DirectoryNotFoundException($"devkitPPC bin path not found: {DevKitBinPath} (set DEVKITPPC or install devkitPPC)");
        if (!File.Exists(GetToolPath("powerpc-eabi-gcc")))
            throw new FileNotFoundException($"powerpc-eabi-gcc not found in {DevKitBinPath}");
    }
}
