using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using WWOnline.Patcher.Config;
using WWOnline.Patcher.Patches;

namespace WWOnline.Patcher.Pipeline;

/// <summary>
/// Records which C/ASM sources and which optional patches a patched game was built from, so the
/// client and the dev-test script can refuse to run against a game build that no longer matches
/// (e.g. puppet_shared.h changed but nobody re-patched, the player changed their optional patch
/// selection, or an app update shipped new game-side code).
///
/// The stamp lives next to the patched game at &lt;GamePath&gt;/wwo-build-stamp.json and is
/// written only after a successful Full build (or a pre-built patch from the client). Any other
/// run deletes it first, because a partial build (Compile / Patches) leaves the game in a state
/// no stamp describes.
///
/// The source hash has one definition (<see cref="ComputeSourceHash(IEnumerable{SourceEntry}, IEnumerable{string})"/>)
/// over per-file content hashes. The live pipeline hashes GameMod/ directly; a pre-built PatchData
/// folder carries the same per-file hashes in its <see cref="PatchDataStamp"/>, so both give the same
/// hash for the same sources and selection.
/// </summary>
public static class BuildStamp
{
    public const string FileName = "wwo-build-stamp.json";

    /// <summary>Generated by the pipeline itself — hashing it would make every build look stale.</summary>
    private static readonly string[] GeneratedFiles = [PatcherConfig.HookAsmFileName];

    public enum Status { Fresh, Stale, Missing }

    /// <param name="SourceHash">Hash of the sources (required + the selected optional patches).</param>
    /// <param name="OptionalPatches">Optional patch ids the game was built with (null in stamps from before optional patches).</param>
    /// <param name="Origin">"pipeline" (live compile) or "prebuilt" (client fallback from PatchData/).</param>
    public sealed record Stamp(string SourceHash, DateTime BuiltAtUtc, int FileCount,
        string[]? OptionalPatches = null, string? Origin = null);

    /// <param name="AgainstPatchData">Compared with a pre-built PatchData stamp (installed app), not GameMod sources.</param>
    public sealed record CheckResult(Status Status, string CurrentHash, Stamp? Recorded,
        bool SelectionChanged = false, IReadOnlyList<string>? DesiredPatches = null, bool AgainstPatchData = false)
    {
        public IReadOnlyList<string> RecordedPatches => Recorded?.OptionalPatches ?? [];

        public string Describe()
        {
            if (Status == Status.Missing)
                return "game build has no build stamp (never fully patched by this pipeline, or a partial build ran). Re-patch the game.";
            var patches = RecordedPatches.Count == 0 ? "none" : string.Join(", ", RecordedPatches);
            if (SelectionChanged)
                return $"game build is STALE: it was built with optional patches [{patches}] but [{string.Join(", ", DesiredPatches ?? [])}] " +
                       "are selected now. Re-patch the game.";
            if (Status == Status.Fresh)
                return $"game build is up to date (sources {Short(CurrentHash)}, optional patches [{patches}], built {Recorded!.BuiltAtUtc:u})";
            return AgainstPatchData
                ? $"game build is STALE: this version of the app has new game code (patch data {Short(CurrentHash)}), but the game was " +
                  $"patched from {Short(Recorded!.SourceHash)} at {Recorded.BuiltAtUtc:u}. Patch the game again."
                : $"game build is STALE: sources are {Short(CurrentHash)} but the game was built from " +
                  $"{Short(Recorded!.SourceHash)} at {Recorded.BuiltAtUtc:u}. Re-patch the game.";
        }

        private static string Short(string hash) => hash[..Math.Min(12, hash.Length)];
    }

    /// <summary>
    /// One hashed source file: its path relative to GameMod/ ('/'-separated) and the SHA-256 of its
    /// content (line endings normalised for text files).
    /// </summary>
    public sealed record SourceEntry(string Path, string Sha256);

    /// <summary>
    /// Inputs every build uses, whatever the selection: puppet C sources + headers, required ASM
    /// patches (not the generated link_draw_hook.asm), free_space_start_offsets.txt, and the
    /// GameMod/include headers / linker script.
    /// </summary>
    public static IReadOnlyList<string> GetRequiredSourceFiles(PatcherConfig config)
    {
        var files = new List<string>();
        AddFiles(files, config.PuppetLinkSrcPath, "*.c", "*.h");
        AddFiles(files, config.PatchesSrcPath, "*.asm");
        AddFiles(files, config.IncludePath, "*.h", "*.ld");
        if (File.Exists(config.FreeSpaceOffsetsPath)) files.Add(config.FreeSpaceOffsetsPath);
        files.RemoveAll(f => GeneratedFiles.Contains(Path.GetFileName(f), StringComparer.OrdinalIgnoreCase));
        return Sorted(files);
    }

    /// <summary>One optional patch's inputs: its .asm and any GameMod/assets file its @edit lines copy.</summary>
    public static IReadOnlyList<string> GetOptionalPatchSourceFiles(PatcherConfig config, string id)
    {
        var path = Path.Combine(config.OptionalPatchesSrcPath, id + ".asm");
        if (!File.Exists(path)) return [];
        var files = new List<string> { path };
        foreach (var edit in OptionalPatchCatalog.ParseFile(path).Edits.OfType<ReplaceFileEdit>())
        {
            var asset = Path.Combine(config.AssetsPath, edit.AssetName);
            if (File.Exists(asset)) files.Add(asset);
        }
        return Sorted(files);
    }

    /// <summary>
    /// Every input that affects the patched game for a given optional selection: the required
    /// sources plus the selected optional patches (+ any assets their @edit lines copy).
    /// </summary>
    public static IReadOnlyList<string> GetSourceFiles(PatcherConfig config, IReadOnlyCollection<string> optionalPatchIds) =>
        Sorted(GetRequiredSourceFiles(config).Concat(optionalPatchIds.SelectMany(id => GetOptionalPatchSourceFiles(config, id))));

    /// <summary>Sources for the selection <paramref name="config"/> would build (its OptionalPatches, or the defaults).</summary>
    public static IReadOnlyList<string> GetSourceFiles(PatcherConfig config) =>
        GetSourceFiles(config, config.LoadOptionalPatchCatalog().Resolve(config.OptionalPatches).Ids);

    public static string ComputeSourceHash(PatcherConfig config) =>
        ComputeSourceHash(config, config.LoadOptionalPatchCatalog().Resolve(config.OptionalPatches).Ids);

    public static string ComputeSourceHash(PatcherConfig config, IReadOnlyCollection<string> optionalPatchIds) =>
        ComputeSourceHash(HashSourceFiles(config, GetSourceFiles(config, optionalPatchIds)), optionalPatchIds);

    /// <summary>
    /// The source hash of a build: SHA-256 over each entry's relative path and content hash (ordinal
    /// path order, duplicates dropped) followed by the selected optional patch ids. The one
    /// definition shared by the live pipeline and pre-built PatchData stamps.
    /// </summary>
    public static string ComputeSourceHash(IEnumerable<SourceEntry> entries, IEnumerable<string> optionalPatchIds)
    {
        var manifest = new StringBuilder();
        foreach (var entry in entries.DistinctBy(e => e.Path).OrderBy(e => e.Path, StringComparer.Ordinal))
            manifest.Append(entry.Path).Append('\n').Append(entry.Sha256).Append('\n');
        // The selection itself is an input too (covers ids whose .asm has vanished).
        var ids = optionalPatchIds.Distinct(StringComparer.Ordinal).OrderBy(i => i, StringComparer.Ordinal);
        manifest.Append("optional:").Append(string.Join(",", ids));
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(manifest.ToString()))).ToLowerInvariant();
    }

    public static IReadOnlyList<SourceEntry> HashSourceFiles(PatcherConfig config, IEnumerable<string> files) =>
        files.Select(f => HashSourceFile(config, f)).ToList();

    /// <summary>The entry for one file under GameMod/.</summary>
    public static SourceEntry HashSourceFile(PatcherConfig config, string file)
    {
        var relative = Path.GetRelativePath(config.GameModPath, file).Replace('\\', '/');
        // Normalise line endings so a git autocrlf round-trip doesn't read as a source change.
        var bytes = File.ReadAllBytes(file);
        var content = IsText(file) ? bytes.Where(b => b != (byte)'\r').ToArray() : bytes;
        return new SourceEntry(relative, Convert.ToHexString(SHA256.HashData(content)).ToLowerInvariant());
    }

    private static bool IsText(string file) => Path.GetExtension(file).ToLowerInvariant() is ".c" or ".h" or ".asm" or ".ld" or ".txt";

    public static string GetStampPath(PatcherConfig config) => GetStampPath(config.GamePath);
    public static string GetStampPath(string gamePath) => Path.Combine(gamePath, FileName);

    /// <summary>Stamp a completed Full build of <paramref name="config"/>'s selection.</summary>
    public static void Write(PatcherConfig config)
    {
        var ids = config.LoadOptionalPatchCatalog().Resolve(config.OptionalPatches).Ids;
        Write(config.GamePath, new Stamp(ComputeSourceHash(config, ids), DateTime.UtcNow,
            GetSourceFiles(config, ids).Count, ids.ToArray(), "pipeline"));
    }

    public static void Write(string gamePath, Stamp stamp) =>
        File.WriteAllText(GetStampPath(gamePath), JsonSerializer.Serialize(stamp, new JsonSerializerOptions { WriteIndented = true }));

    public static void Delete(PatcherConfig config) => Delete(config.GamePath);

    public static void Delete(string gamePath)
    {
        var path = GetStampPath(gamePath);
        if (File.Exists(path)) File.Delete(path);
    }

    public static Stamp? Read(PatcherConfig config) => Read(config.GamePath);

    public static Stamp? Read(string gamePath)
    {
        var path = GetStampPath(gamePath);
        if (!File.Exists(path)) return null;
        try { return JsonSerializer.Deserialize<Stamp>(File.ReadAllText(path)); }
        catch (JsonException) { return null; }
    }

    /// <summary>
    /// Is the game at config.GamePath built from the current sources? The source hash is computed
    /// for the optional patches the game was built with, so editing an unselected patch doesn't
    /// make it stale. When <paramref name="desiredOptionalPatches"/> is given (null = don't compare),
    /// a different selection also reports Stale (SelectionChanged).
    /// </summary>
    public static CheckResult Check(PatcherConfig config, IEnumerable<string>? desiredOptionalPatches = null)
    {
        var catalog = config.LoadOptionalPatchCatalog();
        var recorded = Read(config);
        var desired = desiredOptionalPatches == null ? null : catalog.Resolve(desiredOptionalPatches).Ids;
        if (recorded == null)
            return new CheckResult(Status.Missing, ComputeSourceHash(config, desired ?? catalog.DefaultIds), null, DesiredPatches: desired);

        var recordedIds = recorded.OptionalPatches ?? [];
        var current = ComputeSourceHash(config, recordedIds);
        var selectionChanged = desired != null && !SameSelection(desired, recordedIds);
        var fresh = recorded.SourceHash == current && !selectionChanged;
        return new CheckResult(fresh ? Status.Fresh : Status.Stale, current, recorded, selectionChanged, desired);
    }

    /// <summary>
    /// Is the game at <paramref name="gamePath"/> built from this app's pre-built PatchData? For
    /// installed apps, which have no GameMod sources: the game's stamp is compared with the hash the
    /// PatchData stamp gives for the selection the game was built with. An app update that changed
    /// the game-side code (REL, hook, required or selected optional patches) reads as Stale; one
    /// that didn't stays Fresh. <paramref name="desiredOptionalPatches"/> works as in <see cref="Check"/>.
    /// </summary>
    public static CheckResult CheckAgainstPatchData(string gamePath, PatchDataStamp patchData,
        IReadOnlyCollection<string>? desiredOptionalPatches = null)
    {
        var recorded = Read(gamePath);
        var desired = desiredOptionalPatches?.Distinct(StringComparer.Ordinal).OrderBy(i => i, StringComparer.Ordinal).ToList();
        if (recorded == null)
            return new CheckResult(Status.Missing, patchData.ComputeSourceHash(desired ?? patchData.DefaultOptionalPatches.ToList()), null,
                DesiredPatches: desired, AgainstPatchData: true);

        var recordedIds = recorded.OptionalPatches ?? [];
        var current = patchData.ComputeSourceHash(recordedIds);
        var selectionChanged = desired != null && !SameSelection(desired, recordedIds);
        var fresh = recorded.SourceHash == current && !selectionChanged;
        return new CheckResult(fresh ? Status.Fresh : Status.Stale, current, recorded, selectionChanged, desired, AgainstPatchData: true);
    }

    /// <summary>Selection-only check for a game folder (no GameMod sources and no PatchData stamp).</summary>
    public static CheckResult CheckSelection(string gamePath, IReadOnlyCollection<string> desiredOptionalPatches)
    {
        var recorded = Read(gamePath);
        if (recorded == null) return new CheckResult(Status.Missing, "", null, DesiredPatches: desiredOptionalPatches.ToList());
        var changed = !SameSelection(desiredOptionalPatches, recorded.OptionalPatches ?? []);
        return new CheckResult(changed ? Status.Stale : Status.Fresh, recorded.SourceHash, recorded, changed, desiredOptionalPatches.ToList());
    }

    public static bool SameSelection(IEnumerable<string> a, IEnumerable<string> b) =>
        new HashSet<string>(a, StringComparer.Ordinal).SetEquals(b);

    private static IReadOnlyList<string> Sorted(IEnumerable<string> files) =>
        files.Distinct(StringComparer.Ordinal).OrderBy(f => f, StringComparer.Ordinal).ToList();

    private static void AddFiles(List<string> files, string dir, params string[] patterns)
    {
        if (!Directory.Exists(dir)) return;
        foreach (var pattern in patterns)
            files.AddRange(Directory.GetFiles(dir, pattern, SearchOption.TopDirectoryOnly));
    }
}
