// <auto-generated>
// Generated from GameMod/src/puppet_link/puppet_shared.h by
// WWOnline.Client/build/PuppetLayout.targets. DO NOT EDIT —
// change the header and rebuild. The header is the single source of truth.
// </auto-generated>
namespace WWOnline.Data;

public static class PuppetLayout
{
    public const int PUPPET_PROC_NAME = 0xB5;
    public const int PUPPET_REL_MODULE_ID = 0x58;
    public const uint PUPPET_SYNC_BASE = 0x803FD000;
    /// <summary>"PUPP"</summary>
    public const int PUPPET_SYNC_MAGIC = 0x50555050;
    public const int PUPPET_MAX_SLOTS = 3;
    public const int PUPPET_HDR_SIZE = 0x10;
    /// <summary>u32</summary>
    public const int PUPPET_HDR_OFF_MAGIC = 0x00;
    /// <summary>u32 — hook keeps slots 0..N-1 spawned; C# writes highest active slot + 1. A spawned slot whose ACTIVE word is 0 is "parked" (no execute/collision, invisible)</summary>
    public const int PUPPET_HDR_OFF_NUM_ACTIVE = 0x04;
    /// <summary>u32</summary>
    public const int PUPPET_HDR_OFF_WRITE_COUNTER = 0x08;
    public const int PUPPET_SLOT_SIZE = 0x50;
    public const uint PUPPET_SLOT_0 = 0x803FD010;
    /// <summary>u32 — set to 1 when slot is live</summary>
    public const int PUPPET_SLOT_OFF_ACTIVE = 0x00;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSX = 0x04;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSY = 0x08;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSZ = 0x0C;
    /// <summary>s16</summary>
    public const int PUPPET_SLOT_OFF_ROTY = 0x10;
    /// <summary>u16</summary>
    public const int PUPPET_SLOT_OFF_ANIM_ID = 0x12;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_ANIM_SPEED = 0x14;
    /// <summary>u32</summary>
    public const int PUPPET_SLOT_OFF_STATE_FLAGS = 0x18;
    /// <summary>u8 — mCurProc, raw daPyProc value</summary>
    public const int PUPPET_SLOT_OFF_CUR_PROC = 0x1C;
    /// <summary>u8 — 0xFF == unequipped</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_SWORD = 0x1D;
    /// <summary>u8 — 0xFF == unequipped</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_SHIELD = 0x1E;
    /// <summary>f32 (compat: same as NEW SPEED_F)</summary>
    public const int PUPPET_SLOT_OFF_VELOCITY_F = 0x20;
    /// <summary>s16</summary>
    public const int PUPPET_SLOT_OFF_STICK_ANGLE = 0x24;
    /// <summary>u16</summary>
    public const int PUPPET_SLOT_OFF_SEQ_NUM = 0x26;
    /// <summary>u8 — APPEARANCE_CLOTHES_* (0=hero, 1=casual, 2=game default)</summary>
    public const int PUPPET_SLOT_OFF_CLOTHES_TYPE = 0x28;
    /// <summary>u8 — tunic colour; TUNIC_COLOR_DEFAULT_* or 0,0,0 = vanilla</summary>
    public const int PUPPET_SLOT_OFF_COLOR_R = 0x29;
    /// <summary>u8</summary>
    public const int PUPPET_SLOT_OFF_COLOR_G = 0x2A;
    /// <summary>u8</summary>
    public const int PUPPET_SLOT_OFF_COLOR_B = 0x2B;
    /// <summary>u16 — peer mEquipItem (Link +0x3560); 0x103 = sword in hand, 0 = not written</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_ITEM = 0x2C;
    /// <summary>u8 — PUPPET_ACTION_FLAG_*</summary>
    public const int PUPPET_SLOT_OFF_ACTION_FLAGS = 0x2E;
    /// <summary>u8 — bumps on every peer proc (re)start (combo swings re-init the same proc)</summary>
    public const int PUPPET_SLOT_OFF_PROC_SEQ = 0x2F;
    /// <summary>peer is guarding (shield up)</summary>
    public const int PUPPET_ACTION_FLAG_GUARD = 0x01;
    /// <summary>f32  (Link +0x254)</summary>
    public const int PUPPET_SLOT_OFF_SPEED_F = 0x30;
    /// <summary>f32  (Link +0x2A8)</summary>
    public const int PUPPET_SLOT_OFF_MAX_NORMAL_SPEED = 0x34;
    /// <summary>f32  (Link +0x35B0)</summary>
    public const int PUPPET_SLOT_OFF_STICK_DISTANCE = 0x38;
    /// <summary>u32  (Link +0x3618)</summary>
    public const int PUPPET_SLOT_OFF_MODE_FLG = 0x3C;
    /// <summary>u32  (Link +0x29C)</summary>
    public const int PUPPET_SLOT_OFF_NO_RESET_FLG0 = 0x40;
    /// <summary>u32  (Link +0x2A0)</summary>
    public const int PUPPET_SLOT_OFF_NO_RESET_FLG1 = 0x44;
    /// <summary>s16  mBodyAngle.x (Link +0x2B4): aim pitch</summary>
    public const int PUPPET_SLOT_OFF_BODY_ANGLE_X = 0x48;
    /// <summary>s16  mBodyAngle.y (Link +0x2B6): aim yaw, relative to shape_angle.y</summary>
    public const int PUPPET_SLOT_OFF_BODY_ANGLE_Y = 0x4A;
    /// <summary>u8   PUPPET_GRAB_KIND_*: what the peer carries (mActorKeepGrab)</summary>
    public const int PUPPET_SLOT_OFF_GRAB_KIND = 0x4C;
    /// <summary>u8   a carried bomb's fuse: frames left (daBomb_c::mRestTime, capped at 255); 0 = none / unknown</summary>
    public const int PUPPET_SLOT_OFF_GRAB_FUSE = 0x4D;
    /// <summary>u16  the peer's boat hull colour, RGB565 (the hull palette's format); 0 = the classic red — last field</summary>
    public const int PUPPET_SLOT_OFF_BOAT_COLOR = 0x4E;
    /// <summary>nothing carried, or something the puppet doesn't draw (pot, barrel...)</summary>
    public const int PUPPET_GRAB_KIND_NONE = 0;
    /// <summary>a bomb (fpcNm_BOMB_e): the REL draws one between the puppet's hands</summary>
    public const int PUPPET_GRAB_KIND_BOMB = 1;
    public const int PUPPET_GRAB_KIND_MAX = 1;
    /// <summary>u32[3] — fopAcM process IDs</summary>
    public const uint PUPPET_PROC_IDS_ADDR = 0x803FD100;
    /// <summary>u32[3] — actor pointers</summary>
    public const uint PUPPET_ACTOR_PTRS_ADDR = 0x803FD10C;
    /// <summary>u32[3] — spawn state machine</summary>
    public const uint PUPPET_SPAWN_STATE_ADDR = 0x803FD118;
    /// <summary>u32 — total spawn counter</summary>
    public const uint PUPPET_SPAWN_COUNTER = 0x803FD124;
    /// <summary>u32 C: anim mirror block (game heap), 0 = none yet</summary>
    public const uint PUPPET_ANM_PTR_ADDR = 0x803FD128;
    /// <summary>"PANM"</summary>
    public const int PUPPET_ANM_MAGIC = 0x50414E4D;
    /// <summary>header + PUPPET_MAX_SLOTS entries (checked below)</summary>
    public const int PUPPET_ANM_BLOCK_SIZE = 0x160;
    /// <summary>u32 C: PUPPET_ANM_MAGIC once set up</summary>
    public const int PUPPET_ANM_OFF_MAGIC = 0x00;
    /// <summary>u32[2] C: __OSStartTime of the boot that allocated it (= PUPPET_NAMES_OFF_BOOT)</summary>
    public const int PUPPET_ANM_OFF_BOOT = 0x08;
    /// <summary>PUPPET_MAX_SLOTS x PUPPET_ANM_SLOT_SIZE</summary>
    public const int PUPPET_ANM_OFF_SLOT0 = 0x10;
    public const int PUPPET_ANM_SLOT_SIZE = 0x70;
    /// <summary>u32 C#: changes with every new sample from the peer (the REL snaps frames only then), never 0; 0 = no data</summary>
    public const int PUPPET_ANM_OFF_SEQ = 0x00;
    /// <summary>u8  mCurProc the anims were sampled with</summary>
    public const int PUPPET_ANM_OFF_PROC = 0x04;
    /// <summary>u8  mLeftHandIdx (+0x34C0): hands.bdl joint of the left hand shape</summary>
    public const int PUPPET_ANM_OFF_HAND_L = 0x05;
    /// <summary>u8  mRightHandIdx (+0x34C1)</summary>
    public const int PUPPET_ANM_OFF_HAND_R = 0x06;
    /// <summary>u16 face btp (LkAnm index): m_tex_anm_heap field_0x2 if set, else mIdx; 0xFFFF none</summary>
    public const int PUPPET_ANM_OFF_TEX_BTP = 0x08;
    /// <summary>u16 eye btk, same from m_tex_scroll_heap</summary>
    public const int PUPPET_ANM_OFF_TEX_BTK = 0x0A;
    /// <summary>u16 m3530</summary>
    public const int PUPPET_ANM_OFF_TEX_BTP_FRAME = 0x0C;
    /// <summary>u16 m3532</summary>
    public const int PUPPET_ANM_OFF_TEX_BTK_FRAME = 0x0E;
    /// <summary>PUPPET_ANM_TRACKS x PUPPET_ANM_TRACK_SIZE</summary>
    public const int PUPPET_ANM_OFF_TRACK0 = 0x10;
    /// <summary>under[0], under[1], upper[0], upper[1] (upper[2] is puppet_held.c's)</summary>
    public const int PUPPET_ANM_TRACKS = 4;
    public const int PUPPET_ANM_TRACK_SIZE = 0x18;
    /// <summary>u16 LkAnm bck index, or PUPPET_ANM_BCK_NONE / _SAME</summary>
    public const int PUPPET_ANM_TR_OFF_BCK = 0x00;
    /// <summary>s16 J3DFrameCtrl::mStart</summary>
    public const int PUPPET_ANM_TR_OFF_START = 0x02;
    /// <summary>s16 mEnd</summary>
    public const int PUPPET_ANM_TR_OFF_END = 0x04;
    /// <summary>s16 mLoop</summary>
    public const int PUPPET_ANM_TR_OFF_LOOP = 0x06;
    /// <summary>u8  mAttribute (J3DFrameCtrl::EMode_*)</summary>
    public const int PUPPET_ANM_TR_OFF_ATTR = 0x08;
    /// <summary>f32 mFrame</summary>
    public const int PUPPET_ANM_TR_OFF_FRAME = 0x0C;
    /// <summary>f32 mRate</summary>
    public const int PUPPET_ANM_TR_OFF_RATE = 0x10;
    /// <summary>f32 mRatio</summary>
    public const int PUPPET_ANM_TR_OFF_RATIO = 0x14;
    /// <summary>no anim on the track (or one the REL can't load: a demo bck)</summary>
    public const int PUPPET_ANM_BCK_NONE = 0xFFFF;
    /// <summary>upper track: plays the under track of the same index</summary>
    public const int PUPPET_ANM_BCK_SAME = 0xFFFE;
    public const int LKANM_BCK_FIRST = 0x008;
    public const int LKANM_BCK_LAST = 0x149;
    public const int LKANM_BTK_FIRST = 0x159;
    public const int LKANM_BTK_LAST = 0x1DA;
    public const int LKANM_BTP_FIRST = 0x1DD;
    public const int LKANM_BTP_LAST = 0x277;
    public const int SPAWN_IDLE = 0;
    public const int SPAWN_SPAWNED = 2;
    public const int SPAWN_FOUND = 3;
    public const uint SCRATCH_REGION_START = 0x803FCFA8;
    public const uint SCRATCH_REGION_END = 0x803FD200;
    /// <summary>u32 — settle delay; C# zeroes on scene change</summary>
    public const uint SPAWN_FRAME_COUNTER_ADDR = 0x803FCFB0;
    /// <summary>u32 — ++ every hook call</summary>
    public const uint FRAME_COUNTER_ADDR = 0x803FD130;
    /// <summary>u32 — hook call counter</summary>
    public const uint COUNTER_ADDR = 0x803FD134;
    /// <summary>u32 — HOOK/TITL/NAME/DONE</summary>
    public const uint STATUS_ADDR = 0x803FD138;
    /// <summary>"HOOK" — drawing Link in a stage</summary>
    public const int STATUS_HOOK = 0x484F4F4B;
    /// <summary>"TITL" — title screen (sea_T)</summary>
    public const int STATUS_TITLE = 0x5449544C;
    /// <summary>"NAME" — file select / name entry</summary>
    public const int STATUS_NAME = 0x4E414D45;
    /// <summary>"DONE" — drew Link with puppets active</summary>
    public const int STATUS_DONE = 0x444F4E45;
    /// <summary>u32 — last daPy_lk_c* seen</summary>
    public const uint DEBUG_PTR_ADDR = 0x803FD13C;
    /// <summary>s32 — last daPy_lk_c::draw result</summary>
    public const uint RESULT_PTR_ADDR = 0x803FD140;
    /// <summary>u32 C: 1 while a swap is in progress, else 0</summary>
    public const uint PUPPET_EQUIP_SWAP_ACTIVE_ADDR = 0x803FD144;
    /// <summary>u32 C: ++ at swap start and end (odd = in progress)</summary>
    public const uint PUPPET_EQUIP_SWAP_SEQ_ADDR = 0x803FD148;
    /// <summary>u32 C: live-world block (game heap), 0 = none yet</summary>
    public const uint LIVEWORLD_PTR_ADDR = 0x803FD14C;
    /// <summary>"LIVE"</summary>
    public const int LIVEWORLD_MAGIC = 0x4C495645;
    /// <summary>"LW" | saveTbl</summary>
    public const int LIVEWORLD_TAG_MAGIC = 0x4C570000;
    public const int LIVEWORLD_BLOCK_SIZE = 0x4C;
    /// <summary>tbox + 8 switch words</summary>
    public const int LIVEWORLD_BIT_WORDS = 9;
    public const int LIVEWORLD_ZONE_ROOM_NONE = 0xFF;
    /// <summary>u32 C: LIVEWORLD_MAGIC once set up</summary>
    public const int LIVEWORLD_OFF_MAGIC = 0x00;
    /// <summary>u32 C#: seqlock, odd while C# writes</summary>
    public const int LIVEWORLD_OFF_SEQ = 0x04;
    /// <summary>u32[2] C: __OSStartTime of the boot that allocated it</summary>
    public const int LIVEWORLD_OFF_BOOT = 0x08;
    /// <summary>u32 C#: LIVEWORLD_TAG_MAGIC | saveTbl the batch belongs to</summary>
    public const int LIVEWORLD_OFF_TAG = 0x10;
    /// <summary>u32 C#: room of the zone bits (words 7, 8), else LIVEWORLD_ZONE_ROOM_NONE</summary>
    public const int LIVEWORLD_OFF_ZONE_ROOM = 0x14;
    /// <summary>u32[9] C#: the batch of new bits (see above)</summary>
    public const int LIVEWORLD_OFF_BITS = 0x18;
    /// <summary>u32 C: SEQ of the last batch handled</summary>
    public const int LIVEWORLD_OFF_DONE_SEQ = 0x3C;
    /// <summary>u32 C: ++ per actor re-created or unlocked</summary>
    public const int LIVEWORLD_OFF_POKE_COUNT = 0x40;
    /// <summary>u32 C: passes held back for an actor still being created</summary>
    public const int LIVEWORLD_OFF_WAIT = 0x44;
    /// <summary>u32 C: with DONE_SEQ: actors left undone (not ready in ~2 s, hits full, delete refused): publish again</summary>
    public const int LIVEWORLD_OFF_RETRY = 0x48;
    /// <summary>u32 C#: LOCAL_APPEARANCE_MAGIC while WORD is valid (else REL uses game default + vanilla colour)</summary>
    public const uint LOCAL_APPEARANCE_TAG_ADDR = 0x803FD150;
    /// <summary>"LAPP"</summary>
    public const int LOCAL_APPEARANCE_MAGIC = 0x4C415050;
    /// <summary>u32 C#: (clothes &lt;&lt; 24) | (R &lt;&lt; 16) | (G &lt;&lt; 8) | B — clothes = APPEARANCE_CLOTHES_*</summary>
    public const uint LOCAL_APPEARANCE_WORD_ADDR = 0x803FD154;
    /// <summary>u32 C: game-heap block with the local Link's recoloured tunic; outlives the REL, the next REL adopts it. 0 = none</summary>
    public const uint LOCAL_APPEARANCE_BLOCK_ADDR = 0x803FD158;
    /// <summary>u32 C: image the local hero header points at while recoloured, else 0 (C# compares with the live header)</summary>
    public const uint LOCAL_APPEARANCE_IMAGE_ADDR = 0x803FD15C;
    /// <summary>u32 C: colour (0xRRGGBB) in IMAGE, 0 = vanilla</summary>
    public const uint LOCAL_APPEARANCE_APPLIED_ADDR = 0x803FD160;
    /// <summary>u32 C: LOCAL_APPEARANCE_STATUS_* bits, diagnostics only (0 when the REL is not running)</summary>
    public const uint LOCAL_APPEARANCE_STATUS_ADDR = 0x803FD164;
    /// <summary>headers captured, REL owns the local Link's outfit/colour</summary>
    public const int LOCAL_APPEARANCE_STATUS_ACTIVE = 0x01;
    /// <summary>local Link is in casual clothes</summary>
    public const int LOCAL_APPEARANCE_STATUS_CASUAL = 0x02;
    /// <summary>local hero tunic is recoloured</summary>
    public const int LOCAL_APPEARANCE_STATUS_COLOR = 0x04;
    /// <summary>outfit change waiting for the running event to end</summary>
    public const int LOCAL_APPEARANCE_STATUS_DEFERRED = 0x08;
    /// <summary>u32 C: names block (game heap), 0 = none yet</summary>
    public const uint PUPPET_NAMES_PTR_ADDR = 0x803FD168;
    /// <summary>"NAME"</summary>
    public const int PUPPET_NAMES_MAGIC = 0x4E414D45;
    /// <summary>header + PUPPET_MAX_SLOTS names</summary>
    public const int PUPPET_NAMES_BLOCK_SIZE = 0x58;
    /// <summary>u32 C: PUPPET_NAMES_MAGIC once the block is set up</summary>
    public const int PUPPET_NAMES_OFF_MAGIC = 0x00;
    /// <summary>u32 C#: PUPPET_NAMES_FLAG_* (0 in a new block)</summary>
    public const int PUPPET_NAMES_OFF_FLAGS = 0x04;
    /// <summary>u32[2] C: __OSStartTime (u64) of the boot that allocated the block</summary>
    public const int PUPPET_NAMES_OFF_BOOT = 0x08;
    /// <summary>char[PUPPET_NAME_BYTES] per slot, slot i at + i * PUPPET_NAME_BYTES</summary>
    public const int PUPPET_NAMES_OFF_NAME0 = 0x10;
    /// <summary>per slot, NUL included</summary>
    public const int PUPPET_NAME_BYTES = 24;
    /// <summary>C# truncates names to this many characters</summary>
    public const int PUPPET_NAME_MAX_CHARS = 16;
    /// <summary>the local player wants names shown ("Show player names")</summary>
    public const int PUPPET_NAMES_FLAG_SHOW = 0x01;
    /// <summary>u32 C: events block (game heap), 0 = none yet</summary>
    public const uint PUPPET_FX_PTR_ADDR = 0x803FD16C;
    /// <summary>"PFX0"</summary>
    public const int PUPPET_FX_MAGIC = 0x50465830;
    /// <summary>header + inbox + outbox (checked below)</summary>
    public const int PUPPET_FX_BLOCK_SIZE = 0x3F0;
    /// <summary>u32 C: PUPPET_FX_MAGIC once the block is set up</summary>
    public const int PUPPET_FX_OFF_MAGIC = 0x00;
    /// <summary>u32 C#: PUPPET_FX_FLAG_* (0 in a new block)</summary>
    public const int PUPPET_FX_OFF_FLAGS = 0x04;
    /// <summary>u32[2] C: __OSStartTime (u64) of the boot that allocated the block (= PUPPET_NAMES_OFF_BOOT: puppet_bootBlock)</summary>
    public const int PUPPET_FX_OFF_BOOT = 0x08;
    /// <summary>u32 C#: seq of the last inbox event written</summary>
    public const int PUPPET_FX_OFF_IN_WRITE = 0x10;
    /// <summary>u32 C: seq of the last inbox event consumed</summary>
    public const int PUPPET_FX_OFF_IN_READ = 0x14;
    /// <summary>u32 C: seq of the last outbox event written</summary>
    public const int PUPPET_FX_OFF_OUT_WRITE = 0x18;
    /// <summary>u32 C#: seq of the last outbox event read (the ack)</summary>
    public const int PUPPET_FX_OFF_OUT_READ = 0x1C;
    /// <summary>u32 C: outbox events dropped (ring full), diagnostics</summary>
    public const int PUPPET_FX_OFF_OUT_DROPPED = 0x20;
    /// <summary>u32 C: inbox events refused (bad values, slot not shown, table full)</summary>
    public const int PUPPET_FX_OFF_IN_REJECTED = 0x24;
    /// <summary>u32 C: projectiles spawned for peers, diagnostics</summary>
    public const int PUPPET_FX_OFF_SPAWNED = 0x28;
    /// <summary>PUPPET_FX_IN_COUNT events</summary>
    public const int PUPPET_FX_OFF_IN_RING = 0x30;
    public const int PUPPET_FX_IN_COUNT = 16;
    /// <summary>PUPPET_FX_OUT_COUNT events</summary>
    public const int PUPPET_FX_OFF_OUT_RING = 0x2B0;
    public const int PUPPET_FX_OUT_COUNT = 8;
    public const int PUPPET_FX_EVENT_SIZE = 0x28;
    /// <summary>the room's SharedProjectiles rule is on: report the local Link's projectiles</summary>
    public const int PUPPET_FX_FLAG_SEND = 0x01;
    /// <summary>u8  PUPPET_FX_KIND_*</summary>
    public const int PUPPET_FX_EV_OFF_KIND = 0x00;
    /// <summary>u8  inbox: the sender's puppet slot; outbox: 0</summary>
    public const int PUPPET_FX_EV_OFF_SLOT = 0x01;
    /// <summary>u8  ARROW: the arrow type (daArrow_c::mArrowType, 0..3); 0 for bombs and cannonballs</summary>
    public const int PUPPET_FX_EV_OFF_VARIANT = 0x02;
    /// <summary>s8  outbox: the projectile's room (current.roomNo) when it happened, -1 unknown; inbox: 0</summary>
    public const int PUPPET_FX_EV_OFF_ROOM = 0x03;
    /// <summary>u32 the sender's projectile: its actor's process id there</summary>
    public const int PUPPET_FX_EV_OFF_ID = 0x04;
    /// <summary>f32 current.pos</summary>
    public const int PUPPET_FX_EV_OFF_POSX = 0x08;
    /// <summary>f32</summary>
    public const int PUPPET_FX_EV_OFF_POSY = 0x0C;
    /// <summary>f32</summary>
    public const int PUPPET_FX_EV_OFF_POSZ = 0x10;
    /// <summary>f32 speedF</summary>
    public const int PUPPET_FX_EV_OFF_SPEED_F = 0x14;
    /// <summary>f32 speed.y</summary>
    public const int PUPPET_FX_EV_OFF_SPEED_Y = 0x18;
    /// <summary>f32 gravity</summary>
    public const int PUPPET_FX_EV_OFF_GRAVITY = 0x1C;
    /// <summary>s16 current.angle.x</summary>
    public const int PUPPET_FX_EV_OFF_ANGLE_X = 0x20;
    /// <summary>s16 current.angle.y</summary>
    public const int PUPPET_FX_EV_OFF_ANGLE_Y = 0x22;
    /// <summary>s16 shape_angle.z</summary>
    public const int PUPPET_FX_EV_OFF_ANGLE_Z = 0x24;
    /// <summary>s16 bomb: fuse frames left (mRestTime); cannonball: frames without gravity</summary>
    public const int PUPPET_FX_EV_OFF_TIMER = 0x26;
    /// <summary>a bomb left the sender's hands (thrown / put down): spawn or snap a lit bomb in flight</summary>
    public const int PUPPET_FX_KIND_BOMB_THROW = 1;
    /// <summary>the sender picked their bomb up again: delete the copy (the puppet shows it carried)</summary>
    public const int PUPPET_FX_KIND_BOMB_PICKUP = 2;
    /// <summary>the sender's bomb / cannonball exploded at POS: explode the copy there, or an explosion</summary>
    public const int PUPPET_FX_KIND_EXPLODE = 3;
    /// <summary>the sender's bomb / cannonball is gone without exploding (sank): the copy goes</summary>
    public const int PUPPET_FX_KIND_REMOVE = 4;
    /// <summary>the sender's boat cannon fired: spawn the cannonball in flight</summary>
    public const int PUPPET_FX_KIND_CANNON = 5;
    /// <summary>the sender shot an arrow (VARIANT = type) from POS along ANGLE_X/Y: spawn it in flight</summary>
    public const int PUPPET_FX_KIND_ARROW = 6;
    public const int PUPPET_FX_KIND_MAX = 6;
    /// <summary>light</summary>
    public const int PUPPET_FX_ARROW_TYPE_MAX = 3;
    public const int APPEARANCE_CLOTHES_HERO = 0;
    public const int APPEARANCE_CLOTHES_CASUAL = 1;
    /// <summary>follow the save: playerInit's rule, d_a_player_main.cpp:12362</summary>
    public const int APPEARANCE_CLOTHES_DEFAULT = 2;
    public const int TUNIC_COLOR_DEFAULT_R = 30;
    public const int TUNIC_COLOR_DEFAULT_G = 100;
    public const int TUNIC_COLOR_DEFAULT_B = 35;
    public const int EVENT_BIT_HERO_CLOTHES = 0x2A80;
    /// <summary>daPyFlg1_CASUAL_CLOTHES on mNoResetFlg1 (d_a_player.h:202)</summary>
    public const int DAPY_FLG1_CASUAL_CLOTHES = 0x08;
    /// <summary>ResTIMG::imageOffset, relative to the header (JUTTexture.h:36)</summary>
    public const int RESTIMG_OFF_IMAGE_OFFSET = 0x1C;
    public const uint PUPPET_BOAT_0 = 0x803FD170;
    /// <summary>3 slots end at 0x803FD1D0; 0x803FD1D0..DF is reserved (docs/small-keys.md)</summary>
    public const int PUPPET_BOAT_SIZE = 0x20;
    /// <summary>u32 — PUPPET_BOAT_FLAG_*</summary>
    public const int PUPPET_BOAT_OFF_FLAGS = 0x00;
    /// <summary>f32 — current.pos</summary>
    public const int PUPPET_BOAT_OFF_POSX = 0x04;
    /// <summary>f32</summary>
    public const int PUPPET_BOAT_OFF_POSY = 0x08;
    /// <summary>f32</summary>
    public const int PUPPET_BOAT_OFF_POSZ = 0x0C;
    /// <summary>f32 — speedF (forward speed, for prediction)</summary>
    public const int PUPPET_BOAT_OFF_SPEED_F = 0x10;
    /// <summary>s16 — shape_angle.y</summary>
    public const int PUPPET_BOAT_OFF_ROTY = 0x14;
    /// <summary>s16 — mSailAngle: J_FN_SAIL1 turns by -this about Z</summary>
    public const int PUPPET_BOAT_OFF_SAIL_ANGLE = 0x16;
    /// <summary>s16 — m0366: J_FN_STEER1 / J_FN_KAJI turn by this about Z</summary>
    public const int PUPPET_BOAT_OFF_TILLER = 0x18;
    /// <summary>s16 — m03A0: head look pitch (headJointCallBack1, J_FN_KUBI1..6)</summary>
    public const int PUPPET_BOAT_OFF_HEAD_X = 0x1A;
    /// <summary>s16 — m03A2: head look yaw</summary>
    public const int PUPPET_BOAT_OFF_HEAD_Y = 0x1C;
    /// <summary>u8  — mpBodyAnm frame (the mast bck), whole frames</summary>
    public const int PUPPET_BOAT_OFF_MAST_FRAME = 0x1E;
    /// <summary>u8  — mpHeadAnm frame, whole frames</summary>
    public const int PUPPET_BOAT_OFF_HEAD_FRAME = 0x1F;
    /// <summary>the peer has a boat to show: riding it, or PARKED</summary>
    public const int PUPPET_BOAT_FLAG_ACTIVE = 0x01;
    /// <summary>daShip_c mStateFlag daSFLG_FLY_e: airborne, use POSY</summary>
    public const int PUPPET_BOAT_FLAG_FLY = 0x02;
    /// <summary>m0392 == SHIP_BCK_MAST_ON2 (mast up / rising), else SHIP_BCK_MAST_OFF2</summary>
    public const int PUPPET_BOAT_FLAG_MAST_ON = 0x04;
    /// <summary>m03E8 == 0.001: J_FN_MAST scaled away (cannon or crane in its place)</summary>
    public const int PUPPET_BOAT_FLAG_MAST_HIDE = 0x08;
    /// <summary>nobody aboard: they got off on the Great Sea; drawn empty, never seats the puppet</summary>
    public const int PUPPET_BOAT_FLAG_PARKED = 0x40;
    public const int PUPPET_BOAT_PART_SHIFT = 4;
    public const int PUPPET_BOAT_PART_MASK = 0x3;
    public const int PUPPET_BOAT_HEAD_BCK_SHIFT = 8;
    public const int PUPPET_BOAT_HEAD_BCK_MASK = 0xFF;
    /// <summary>AKIBI1: first bck in the archive</summary>
    public const int SHIP_BCK_FIRST = 0x05;
    public const int SHIP_BCK_DAMAGE1 = 0x06;
    /// <summary>the head's resting bck (daShip_c::createHeap)</summary>
    public const int SHIP_BCK_FN_LOOK_L = 0x07;
    public const int SHIP_BCK_MAST_OFF2 = 0x0A;
    public const int SHIP_BCK_MAST_ON2 = 0x0B;
    /// <summary>KYAKKAN1: last bck in the archive</summary>
    public const int SHIP_BCK_LAST = 0x0E;
    public const int SHIP_PART_WAIT = 0;
    /// <summary>the sail</summary>
    public const int SHIP_PART_STEER = 1;
    public const int SHIP_PART_CANNON = 2;
    /// <summary>the salvage arm</summary>
    public const int SHIP_PART_CRANE = 3;
    /// <summary>mRopeCnt's cap: ARRAY_SIZE(mRopeLineSegments) (d_a_ship.cpp:3108-3109)</summary>
    public const int SHIP_ROPE_MAX = 250;
    public const uint PUPPET_BOAT_CANNON_0 = 0x803FCFB4;
    /// <summary>3 slots end at 0x803FCFC0 = DBG_MAGIC_DETECTED_ADDR</summary>
    public const int PUPPET_BOAT_CANNON_SIZE = 0x04;
    /// <summary>s16 — m0394: VFNCN J CANON1 turns by this about X</summary>
    public const int PUPPET_BOAT_CANNON_OFF_YAW = 0x00;
    /// <summary>s16 — m0396: J CANON2 turns by -this about Y (0..0x4000)</summary>
    public const int PUPPET_BOAT_CANNON_OFF_PITCH = 0x02;
    public const uint PUPPET_BOAT_CRANE_0 = 0x803FCFE0;
    /// <summary>3 slots end at 0x803FCFEC = CLIENT_HEARTBEAT_ADDR</summary>
    public const int PUPPET_BOAT_CRANE_SIZE = 0x04;
    /// <summary>s16 — m0398 + m039C: VFNCR V_CRANE_ROTATION turns by -this about Z</summary>
    public const int PUPPET_BOAT_CRANE_OFF_ANGLE = 0x00;
    /// <summary>u8  — mRopeCnt: 10-unit rope segments (0..SHIP_ROPE_MAX); 0x03 is spare</summary>
    public const int PUPPET_BOAT_CRANE_OFF_ROPE = 0x02;
    /// <summary>u32 — times magic marker seen</summary>
    public const uint DBG_MAGIC_DETECTED_ADDR = 0x803FCFC0;
    /// <summary>u32 — fopAcM_create attempts</summary>
    public const uint DBG_CREATE_ATTEMPTS_ADDR = 0x803FCFC4;
    /// <summary>u32 — fopAcM_create successes</summary>
    public const uint DBG_CREATE_SUCCESSES_ADDR = 0x803FCFC8;
    /// <summary>u32 — fopAcM_create failures</summary>
    public const uint DBG_CREATE_FAILURES_ADDR = 0x803FCFCC;
    /// <summary>u32 — last desiredCount from header</summary>
    public const uint DBG_LAST_DESIRED_ADDR = 0x803FCFD0;
    /// <summary>u32 — last PID from fopAcM_create</summary>
    public const uint DBG_LAST_PID_ADDR = 0x803FCFD4;
    /// <summary>u32 — puppet deletes issued</summary>
    public const uint DBG_DELETE_ISSUED_ADDR = 0x803FCFD8;
    /// <summary>u32 C#: remote-collected mItem bits 0..31</summary>
    public const uint WORLDSYNC_ITEM_MASK_ADDR = 0x803FD1E0;
    /// <summary>u32 C#: WORLDSYNC_TAG_MAGIC | saveTbl, else mask ignored</summary>
    public const uint WORLDSYNC_STAGE_TAG_ADDR = 0x803FD1E4;
    /// <summary>"WS"</summary>
    public const int WORLDSYNC_TAG_MAGIC = 0x57530000;
    /// <summary>u32 C: ++ per despawn</summary>
    public const uint WORLDSYNC_DESPAWN_COUNT_ADDR = 0x803FD1E8;
    /// <summary>u32 C: (saveTbl&lt;&lt;16)|(itemNo&lt;&lt;8)|bit</summary>
    public const uint WORLDSYNC_LAST_DESPAWN_ADDR = 0x803FD1EC;
    /// <summary>u32 C: matching placed items still alive after the scan</summary>
    public const uint WORLDSYNC_PENDING_ADDR = 0x803FD1F0;
    /// <summary>u32 C: ++ per completed scan</summary>
    public const uint WORLDSYNC_SCAN_SEQ_ADDR = 0x803FD1F4;
    /// <summary>u32 C: the stage tag the scan used</summary>
    public const uint WORLDSYNC_SCAN_TAG_ADDR = 0x803FD1F8;
    /// <summary>u32 C: candidates the scan used (mask &amp; live mItem[0])</summary>
    public const uint WORLDSYNC_SCAN_CAND_ADDR = 0x803FD1FC;
    /// <summary>u32 — slot 0 visibility-gate bitmap</summary>
    public const uint CLIENT_DBG_SLOT0_GATES = 0x803FCFDC;
    /// <summary>u32 — ++ every client sync tick</summary>
    public const uint CLIENT_HEARTBEAT_ADDR = 0x803FCFEC;
    /// <summary>u32 — ticks spent in unstable/hold branch</summary>
    public const uint CLIENT_DBG_UNSTABLE_HITS = 0x803FCFF0;
    /// <summary>u32 — bit0 stable, bit1 sceneChanged, bit2 linkAlive</summary>
    public const uint CLIENT_DBG_STABILITY_BITS = 0x803FCFF4;
    /// <summary>u32 — active count C# last wrote</summary>
    public const uint CLIENT_DBG_LAST_ACTIVE = 0x803FCFF8;
    /// <summary>u32 — C# header write counter</summary>
    public const uint CLIENT_DBG_WRITE_COUNTER = 0x803FCFFC;
    public const int DAPY_OFF_SPEED_F = 0x254;
    public const int DAPY_OFF_NO_RESET_FLG0 = 0x29C;
    public const int DAPY_OFF_NO_RESET_FLG1 = 0x2A0;
    public const int DAPY_OFF_MAX_NORMAL_SPEED = 0x2A8;
    /// <summary>mAnmRatioUnder[0].mRatio</summary>
    public const int DAPY_OFF_ANM_RATIO_UNDER0 = 0x2FB4;
    /// <summary>mAnmRatioUpper[0]</summary>
    public const int DAPY_OFF_ANM_RATIO_UPPER0 = 0x2FC4;
    /// <summary>m_anm_heap_under[0]</summary>
    public const int DAPY_OFF_ANM_HEAP_UNDER0 = 0x2FDC;
    /// <summary>m_anm_heap_upper[0]</summary>
    public const int DAPY_OFF_ANM_HEAP_UPPER0 = 0x2FFC;
    /// <summary>mFrameCtrlUnder[0]</summary>
    public const int DAPY_OFF_FRAME_CTRL_UNDER0 = 0x302C;
    /// <summary>mFrameCtrlUpper[0]</summary>
    public const int DAPY_OFF_FRAME_CTRL_UPPER0 = 0x3054;
    public const int DAPY_ANM_RATIO_SIZE = 0x08;
    public const int DAPY_ANM_HEAP_SIZE = 0x10;
    public const int DAPY_FRAME_CTRL_SIZE = 0x14;
    /// <summary>f32 mRatio</summary>
    public const int ANM_RATIO_OFF_RATIO = 0x00;
    /// <summary>J3DAnmTransform* mAnmTransform</summary>
    public const int ANM_RATIO_OFF_ANM = 0x04;
    /// <summary>u16 mIdx: the LkAnm index loaded, 0xFFFF none</summary>
    public const int ANM_HEAP_OFF_IDX = 0x00;
    /// <summary>u16 field_0x2: a texture heap's priority (setPriTextureAnime) index</summary>
    public const int ANM_HEAP_OFF_PRI_IDX = 0x02;
    /// <summary>u16 field_0x4: a demo (LkD00 archive) id</summary>
    public const int ANM_HEAP_OFF_DEMO_IDX = 0x04;
    /// <summary>void* m_buffer</summary>
    public const int ANM_HEAP_OFF_BUFFER = 0x08;
    /// <summary>JKRSolidHeap* mpAnimeHeap</summary>
    public const int ANM_HEAP_OFF_HEAP = 0x0C;
    /// <summary>u8</summary>
    public const int FRAME_CTRL_OFF_ATTR = 0x04;
    /// <summary>s16</summary>
    public const int FRAME_CTRL_OFF_START = 0x06;
    /// <summary>s16</summary>
    public const int FRAME_CTRL_OFF_END = 0x08;
    /// <summary>s16</summary>
    public const int FRAME_CTRL_OFF_LOOP = 0x0A;
    /// <summary>f32</summary>
    public const int FRAME_CTRL_OFF_RATE = 0x0C;
    /// <summary>f32</summary>
    public const int FRAME_CTRL_OFF_FRAME = 0x10;
    /// <summary>daPy_anmHeap_c m_tex_anm_heap (face btp)</summary>
    public const int DAPY_OFF_TEX_ANM_HEAP = 0x31B8;
    /// <summary>daPy_anmHeap_c m_tex_scroll_heap (eye btk)</summary>
    public const int DAPY_OFF_TEX_SCROLL_HEAP = 0x31C8;
    /// <summary>u8 mLeftHandIdx, then u8 mRightHandIdx</summary>
    public const int DAPY_OFF_HAND_IDX = 0x34C0;
    /// <summary>u16 m3530 (btp frame), then u16 m3532 (btk frame)</summary>
    public const int DAPY_OFF_TEX_FRAMES = 0x3530;
    /// <summary>ResTIMG* mpCurrLinktex — the linktexS3TC header in the shared TEX1</summary>
    public const int DAPY_OFF_CURR_LINKTEX = 0x338;
    public const int DAPY_OFF_CUR_PROC = 0x31D8;
    public const int DAPY_OFF_STICK_DISTANCE = 0x35B0;
    public const int DAPY_OFF_VELOCITY = 0x35BC;
    public const int DAPY_OFF_MODE_FLG = 0x3618;
    /// <summary>u16 mEquipItem</summary>
    public const int DAPY_OFF_EQUIP_ITEM = 0x3560;
    /// <summary>s16 m34E8 — stick direction + camera (what ATN_MOVE blends on)</summary>
    public const int DAPY_OFF_STICK_ANGLE = 0x34E8;
    /// <summary>u16 — m_anm_heap_upper[UPPER_MOVE2].mIdx; guard/REST anims below</summary>
    public const int DAPY_OFF_UPPER_ANM_IDX = 0x301C;
    /// <summary>f32 — mFrameCtrlUnder[0].mFrame; goes backwards on a proc restart</summary>
    public const int DAPY_OFF_UNDER_FRAME = 0x303C;
    /// <summary>u8  — m34C4 combo step (changeCutProc ++)</summary>
    public const int DAPY_OFF_CUT_COMBO = 0x34C4;
    /// <summary>u16 — m3562: item held once the REST (draw/sheathe) anim finishes</summary>
    public const int DAPY_OFF_NEXT_EQUIP_ITEM = 0x3562;
    /// <summary>draw/sheathe upper anim</summary>
    public const int DAPY_UPPER_ANM_REST = 0xD7;
    public const int DAPY_UPPER_ANM_TAKE = 0x103;
    public const int DAPY_UPPER_ANM_TAKEBOTH = 0x104;
    public const int DAPY_UPPER_ANM_TAKEL = 0x105;
    public const int DAPY_UPPER_ANM_TAKER = 0x106;
    /// <summary>s16 — daPy_py_c::mBodyAngle.x (d_a_player.h:491)</summary>
    public const int DAPY_OFF_BODY_ANGLE_X = 0x2B4;
    /// <summary>s16 — mBodyAngle.y</summary>
    public const int DAPY_OFF_BODY_ANGLE_Y = 0x2B6;
    /// <summary>fopAc_ac_c* — mActorKeepGrab (0x318C, d_a_player_main.h:2088) .mActor (+0x4, :86)</summary>
    public const int DAPY_OFF_GRAB_ACTOR = 0x3190;
    /// <summary>s16 — base_process_class::mProcName (f_pc_base.h:16)</summary>
    public const int FPC_OFF_PROC_NAME = 0x08;
    /// <summary>fpcNm_BOMB_e (f_pc_name.h:308)</summary>
    public const int FPC_NAME_BOMB = 0x128;
    /// <summary>s16 — daBomb_c::mRestTime, the fuse (d_a_bomb.h:233; setBombRestTime DOL 0x800681EC: sth r31,0x6FC)</summary>
    public const int DABOMB_OFF_REST_TIME = 0x6FC;
    /// <summary>fpcNm_Bomb2_e (f_pc_name.h:309)</summary>
    public const int FPC_NAME_BOMB2 = 0x129;
    /// <summary>int — Act_c::mState: 0 wait, 1 carry, 2 explode, 3 sink (d_a_bomb2.h; mode_*_init)</summary>
    public const int DABOMB2_OFF_STATE = 0x694;
    /// <summary>int — Act_c::mBombTimer: the fuse in frames, counted down each execute; mode_explode_init zeroes it</summary>
    public const int DABOMB2_OFF_TIMER = 0x738;
    public const int DABOMB2_STATE_EXPLODE = 2;
    public const int DAPY_PROC_GUARD_0 = 0x0C;
    public const int DAPY_PROC_GUARD_1 = 0x0D;
    public const int DAPY_PROC_GUARD_2 = 0x6D;
    public const int DAPY_UPPER_ANM_GUARD_0 = 0x16;
    public const int DAPY_UPPER_ANM_GUARD_1 = 0x1B;
}
