// <auto-generated>
// Generated from GameMod/src/puppet_link/puppet_shared.h by
// WWOnline.Client/build/PuppetLayout.targets. DO NOT EDIT —
// change the header and rebuild. The header is the single source of truth.
// </auto-generated>
namespace WWOnline.Data;

public static class PuppetLayout
{
    public const int PUPPET_PROC_NAME = 0xB5;
    public const int PUPPET_REL_MODULE_ID = 0x58;
    public const uint PUPPET_SYNC_BASE = 0x803FD000;
    /// <summary>"PUPP"</summary>
    public const int PUPPET_SYNC_MAGIC = 0x50555050;
    public const int PUPPET_MAX_SLOTS = 3;
    public const int PUPPET_HDR_SIZE = 0x10;
    /// <summary>u32</summary>
    public const int PUPPET_HDR_OFF_MAGIC = 0x00;
    /// <summary>u32 — hook keeps slots 0..N-1 spawned; C# writes highest active slot + 1. A spawned slot whose ACTIVE word is 0 is "parked" (no execute/collision, invisible)</summary>
    public const int PUPPET_HDR_OFF_NUM_ACTIVE = 0x04;
    /// <summary>u32</summary>
    public const int PUPPET_HDR_OFF_WRITE_COUNTER = 0x08;
    public const int PUPPET_SLOT_SIZE = 0x48;
    public const uint PUPPET_SLOT_0 = 0x803FD010;
    /// <summary>u32 — set to 1 when slot is live</summary>
    public const int PUPPET_SLOT_OFF_ACTIVE = 0x00;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSX = 0x04;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSY = 0x08;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_POSZ = 0x0C;
    /// <summary>s16</summary>
    public const int PUPPET_SLOT_OFF_ROTY = 0x10;
    /// <summary>u16</summary>
    public const int PUPPET_SLOT_OFF_ANIM_ID = 0x12;
    /// <summary>f32</summary>
    public const int PUPPET_SLOT_OFF_ANIM_SPEED = 0x14;
    /// <summary>u32</summary>
    public const int PUPPET_SLOT_OFF_STATE_FLAGS = 0x18;
    /// <summary>u8 — mCurProc, raw daPyProc value</summary>
    public const int PUPPET_SLOT_OFF_CUR_PROC = 0x1C;
    /// <summary>u8 — 0xFF == unequipped</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_SWORD = 0x1D;
    /// <summary>u8 — 0xFF == unequipped</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_SHIELD = 0x1E;
    /// <summary>f32 (compat: same as NEW SPEED_F)</summary>
    public const int PUPPET_SLOT_OFF_VELOCITY_F = 0x20;
    /// <summary>s16</summary>
    public const int PUPPET_SLOT_OFF_STICK_ANGLE = 0x24;
    /// <summary>u16</summary>
    public const int PUPPET_SLOT_OFF_SEQ_NUM = 0x26;
    /// <summary>u8 — APPEARANCE_CLOTHES_* (0=hero, 1=casual, 2=game default)</summary>
    public const int PUPPET_SLOT_OFF_CLOTHES_TYPE = 0x28;
    /// <summary>u8 — tunic colour; TUNIC_COLOR_DEFAULT_* or 0,0,0 = vanilla</summary>
    public const int PUPPET_SLOT_OFF_COLOR_R = 0x29;
    /// <summary>u8</summary>
    public const int PUPPET_SLOT_OFF_COLOR_G = 0x2A;
    /// <summary>u8</summary>
    public const int PUPPET_SLOT_OFF_COLOR_B = 0x2B;
    /// <summary>u16 — peer mEquipItem (Link +0x3560); 0x103 = sword in hand, 0 = not written</summary>
    public const int PUPPET_SLOT_OFF_EQUIP_ITEM = 0x2C;
    /// <summary>u8 — PUPPET_ACTION_FLAG_*</summary>
    public const int PUPPET_SLOT_OFF_ACTION_FLAGS = 0x2E;
    /// <summary>u8 — bumps on every peer proc (re)start (combo swings re-init the same proc)</summary>
    public const int PUPPET_SLOT_OFF_PROC_SEQ = 0x2F;
    /// <summary>peer is guarding (shield up)</summary>
    public const int PUPPET_ACTION_FLAG_GUARD = 0x01;
    /// <summary>f32  (Link +0x254)</summary>
    public const int PUPPET_SLOT_OFF_SPEED_F = 0x30;
    /// <summary>f32  (Link +0x2A8)</summary>
    public const int PUPPET_SLOT_OFF_MAX_NORMAL_SPEED = 0x34;
    /// <summary>f32  (Link +0x35B0)</summary>
    public const int PUPPET_SLOT_OFF_STICK_DISTANCE = 0x38;
    /// <summary>u32  (Link +0x3618)</summary>
    public const int PUPPET_SLOT_OFF_MODE_FLG = 0x3C;
    /// <summary>u32  (Link +0x29C)</summary>
    public const int PUPPET_SLOT_OFF_NO_RESET_FLG0 = 0x40;
    /// <summary>u32  (Link +0x2A0) — last field</summary>
    public const int PUPPET_SLOT_OFF_NO_RESET_FLG1 = 0x44;
    /// <summary>u32[3] — fopAcM process IDs</summary>
    public const uint PUPPET_PROC_IDS_ADDR = 0x803FD100;
    /// <summary>u32[3] — actor pointers</summary>
    public const uint PUPPET_ACTOR_PTRS_ADDR = 0x803FD10C;
    /// <summary>u32[3] — spawn state machine</summary>
    public const uint PUPPET_SPAWN_STATE_ADDR = 0x803FD118;
    /// <summary>u32 — total spawn counter</summary>
    public const uint PUPPET_SPAWN_COUNTER = 0x803FD124;
    public const int SPAWN_IDLE = 0;
    public const int SPAWN_SPAWNED = 2;
    public const int SPAWN_FOUND = 3;
    public const uint SCRATCH_REGION_START = 0x803FCFA8;
    public const uint SCRATCH_REGION_END = 0x803FD200;
    /// <summary>u32 — settle delay; C# zeroes on scene change</summary>
    public const uint SPAWN_FRAME_COUNTER_ADDR = 0x803FCFB0;
    /// <summary>u32 — ++ every hook call</summary>
    public const uint FRAME_COUNTER_ADDR = 0x803FD130;
    /// <summary>u32 — hook call counter</summary>
    public const uint COUNTER_ADDR = 0x803FD134;
    /// <summary>u32 — HOOK/TITL/NAME/DONE</summary>
    public const uint STATUS_ADDR = 0x803FD138;
    /// <summary>u32 — last daPy_lk_c* seen</summary>
    public const uint DEBUG_PTR_ADDR = 0x803FD13C;
    /// <summary>s32 — last daPy_lk_c::draw result</summary>
    public const uint RESULT_PTR_ADDR = 0x803FD140;
    /// <summary>u32 C: 1 while a swap is in progress, else 0</summary>
    public const uint PUPPET_EQUIP_SWAP_ACTIVE_ADDR = 0x803FD144;
    /// <summary>u32 C: ++ at swap start and end (odd = in progress)</summary>
    public const uint PUPPET_EQUIP_SWAP_SEQ_ADDR = 0x803FD148;
    /// <summary>u32 C#: LOCAL_APPEARANCE_MAGIC while WORD is valid (else REL uses game default + vanilla colour)</summary>
    public const uint LOCAL_APPEARANCE_TAG_ADDR = 0x803FD150;
    /// <summary>"LAPP"</summary>
    public const int LOCAL_APPEARANCE_MAGIC = 0x4C415050;
    /// <summary>u32 C#: (clothes &lt;&lt; 24) | (R &lt;&lt; 16) | (G &lt;&lt; 8) | B — clothes = APPEARANCE_CLOTHES_*</summary>
    public const uint LOCAL_APPEARANCE_WORD_ADDR = 0x803FD154;
    /// <summary>u32 C: game-heap block with the local Link's recoloured tunic; outlives the REL, the next REL adopts it. 0 = none</summary>
    public const uint LOCAL_APPEARANCE_BLOCK_ADDR = 0x803FD158;
    /// <summary>u32 C: image the local hero header points at while recoloured, else 0 (C# compares with the live header)</summary>
    public const uint LOCAL_APPEARANCE_IMAGE_ADDR = 0x803FD15C;
    /// <summary>u32 C: colour (0xRRGGBB) in IMAGE, 0 = vanilla</summary>
    public const uint LOCAL_APPEARANCE_APPLIED_ADDR = 0x803FD160;
    /// <summary>u32 C: LOCAL_APPEARANCE_STATUS_* bits, diagnostics only (0 when the REL is not running)</summary>
    public const uint LOCAL_APPEARANCE_STATUS_ADDR = 0x803FD164;
    /// <summary>headers captured, REL owns the local Link's outfit/colour</summary>
    public const int LOCAL_APPEARANCE_STATUS_ACTIVE = 0x01;
    /// <summary>local Link is in casual clothes</summary>
    public const int LOCAL_APPEARANCE_STATUS_CASUAL = 0x02;
    /// <summary>local hero tunic is recoloured</summary>
    public const int LOCAL_APPEARANCE_STATUS_COLOR = 0x04;
    /// <summary>outfit change waiting for the running event to end</summary>
    public const int LOCAL_APPEARANCE_STATUS_DEFERRED = 0x08;
    /// <summary>u32 C: names block (game heap), 0 = none yet</summary>
    public const uint PUPPET_NAMES_PTR_ADDR = 0x803FD168;
    /// <summary>"NAME"</summary>
    public const int PUPPET_NAMES_MAGIC = 0x4E414D45;
    /// <summary>header + PUPPET_MAX_SLOTS names</summary>
    public const int PUPPET_NAMES_BLOCK_SIZE = 0x58;
    /// <summary>u32 C: PUPPET_NAMES_MAGIC once the block is set up</summary>
    public const int PUPPET_NAMES_OFF_MAGIC = 0x00;
    /// <summary>u32 C#: PUPPET_NAMES_FLAG_* (0 in a new block)</summary>
    public const int PUPPET_NAMES_OFF_FLAGS = 0x04;
    /// <summary>u32[2] C: __OSStartTime (u64) of the boot that allocated the block</summary>
    public const int PUPPET_NAMES_OFF_BOOT = 0x08;
    /// <summary>char[PUPPET_NAME_BYTES] per slot, slot i at + i * PUPPET_NAME_BYTES</summary>
    public const int PUPPET_NAMES_OFF_NAME0 = 0x10;
    /// <summary>per slot, NUL included</summary>
    public const int PUPPET_NAME_BYTES = 24;
    /// <summary>C# truncates names to this many characters</summary>
    public const int PUPPET_NAME_MAX_CHARS = 16;
    /// <summary>the local player wants names shown ("Show player names")</summary>
    public const int PUPPET_NAMES_FLAG_SHOW = 0x01;
    public const int APPEARANCE_CLOTHES_HERO = 0;
    public const int APPEARANCE_CLOTHES_CASUAL = 1;
    /// <summary>follow the save: playerInit's rule, d_a_player_main.cpp:12362</summary>
    public const int APPEARANCE_CLOTHES_DEFAULT = 2;
    public const int TUNIC_COLOR_DEFAULT_R = 30;
    public const int TUNIC_COLOR_DEFAULT_G = 100;
    public const int TUNIC_COLOR_DEFAULT_B = 35;
    public const int EVENT_BIT_HERO_CLOTHES = 0x2A80;
    /// <summary>daPyFlg1_CASUAL_CLOTHES on mNoResetFlg1 (d_a_player.h:202)</summary>
    public const int DAPY_FLG1_CASUAL_CLOTHES = 0x08;
    /// <summary>ResTIMG::imageOffset, relative to the header (JUTTexture.h:36)</summary>
    public const int RESTIMG_OFF_IMAGE_OFFSET = 0x1C;
    public const uint PUPPET_BOAT_0 = 0x803FD170;
    /// <summary>3 slots end at 0x803FD1D0; 0x803FD1D0..DF is reserved (docs/small-keys.md)</summary>
    public const int PUPPET_BOAT_SIZE = 0x20;
    /// <summary>u32 — PUPPET_BOAT_FLAG_*</summary>
    public const int PUPPET_BOAT_OFF_FLAGS = 0x00;
    /// <summary>f32 — current.pos</summary>
    public const int PUPPET_BOAT_OFF_POSX = 0x04;
    /// <summary>f32</summary>
    public const int PUPPET_BOAT_OFF_POSY = 0x08;
    /// <summary>f32</summary>
    public const int PUPPET_BOAT_OFF_POSZ = 0x0C;
    /// <summary>f32 — speedF (forward speed, for prediction)</summary>
    public const int PUPPET_BOAT_OFF_SPEED_F = 0x10;
    /// <summary>s16 — shape_angle.y</summary>
    public const int PUPPET_BOAT_OFF_ROTY = 0x14;
    /// <summary>s16 — mSailAngle: J_FN_SAIL1 turns by -this about Z</summary>
    public const int PUPPET_BOAT_OFF_SAIL_ANGLE = 0x16;
    /// <summary>s16 — m0366: J_FN_STEER1 / J_FN_KAJI turn by this about Z</summary>
    public const int PUPPET_BOAT_OFF_TILLER = 0x18;
    /// <summary>s16 — m03A0: head look pitch (headJointCallBack1, J_FN_KUBI1..6)</summary>
    public const int PUPPET_BOAT_OFF_HEAD_X = 0x1A;
    /// <summary>s16 — m03A2: head look yaw</summary>
    public const int PUPPET_BOAT_OFF_HEAD_Y = 0x1C;
    /// <summary>u8  — mpBodyAnm frame (the mast bck), whole frames</summary>
    public const int PUPPET_BOAT_OFF_MAST_FRAME = 0x1E;
    /// <summary>u8  — mpHeadAnm frame, whole frames</summary>
    public const int PUPPET_BOAT_OFF_HEAD_FRAME = 0x1F;
    /// <summary>peer is riding their boat</summary>
    public const int PUPPET_BOAT_FLAG_ACTIVE = 0x01;
    /// <summary>daShip_c mStateFlag daSFLG_FLY_e: airborne, use POSY</summary>
    public const int PUPPET_BOAT_FLAG_FLY = 0x02;
    /// <summary>m0392 == SHIP_BCK_MAST_ON2 (mast up / rising), else SHIP_BCK_MAST_OFF2</summary>
    public const int PUPPET_BOAT_FLAG_MAST_ON = 0x04;
    /// <summary>m03E8 == 0.001: J_FN_MAST scaled away (cannon or crane in its place)</summary>
    public const int PUPPET_BOAT_FLAG_MAST_HIDE = 0x08;
    public const int PUPPET_BOAT_HEAD_BCK_SHIFT = 8;
    public const int PUPPET_BOAT_HEAD_BCK_MASK = 0xFF;
    /// <summary>AKIBI1: first bck in the archive</summary>
    public const int SHIP_BCK_FIRST = 0x05;
    public const int SHIP_BCK_DAMAGE1 = 0x06;
    /// <summary>the head's resting bck (daShip_c::createHeap)</summary>
    public const int SHIP_BCK_FN_LOOK_L = 0x07;
    public const int SHIP_BCK_MAST_OFF2 = 0x0A;
    public const int SHIP_BCK_MAST_ON2 = 0x0B;
    /// <summary>KYAKKAN1: last bck in the archive</summary>
    public const int SHIP_BCK_LAST = 0x0E;
    /// <summary>u32 — times magic marker seen</summary>
    public const uint DBG_MAGIC_DETECTED_ADDR = 0x803FCFC0;
    /// <summary>u32 — fopAcM_create attempts</summary>
    public const uint DBG_CREATE_ATTEMPTS_ADDR = 0x803FCFC4;
    /// <summary>u32 — fopAcM_create successes</summary>
    public const uint DBG_CREATE_SUCCESSES_ADDR = 0x803FCFC8;
    /// <summary>u32 — fopAcM_create failures</summary>
    public const uint DBG_CREATE_FAILURES_ADDR = 0x803FCFCC;
    /// <summary>u32 — last desiredCount from header</summary>
    public const uint DBG_LAST_DESIRED_ADDR = 0x803FCFD0;
    /// <summary>u32 — last PID from fopAcM_create</summary>
    public const uint DBG_LAST_PID_ADDR = 0x803FCFD4;
    /// <summary>u32 — puppet deletes issued</summary>
    public const uint DBG_DELETE_ISSUED_ADDR = 0x803FCFD8;
    /// <summary>u32 C#: remote-collected mItem bits 0..31</summary>
    public const uint WORLDSYNC_ITEM_MASK_ADDR = 0x803FD1E0;
    /// <summary>u32 C#: WORLDSYNC_TAG_MAGIC | saveTbl, else mask ignored</summary>
    public const uint WORLDSYNC_STAGE_TAG_ADDR = 0x803FD1E4;
    /// <summary>"WS"</summary>
    public const int WORLDSYNC_TAG_MAGIC = 0x57530000;
    /// <summary>u32 C: ++ per despawn</summary>
    public const uint WORLDSYNC_DESPAWN_COUNT_ADDR = 0x803FD1E8;
    /// <summary>u32 C: (saveTbl&lt;&lt;16)|(itemNo&lt;&lt;8)|bit</summary>
    public const uint WORLDSYNC_LAST_DESPAWN_ADDR = 0x803FD1EC;
    /// <summary>u32 C: matching placed items still alive after the scan</summary>
    public const uint WORLDSYNC_PENDING_ADDR = 0x803FD1F0;
    /// <summary>u32 C: ++ per completed scan</summary>
    public const uint WORLDSYNC_SCAN_SEQ_ADDR = 0x803FD1F4;
    /// <summary>u32 C: the stage tag the scan used</summary>
    public const uint WORLDSYNC_SCAN_TAG_ADDR = 0x803FD1F8;
    /// <summary>u32 C: candidates the scan used (mask &amp; live mItem[0])</summary>
    public const uint WORLDSYNC_SCAN_CAND_ADDR = 0x803FD1FC;
    /// <summary>u32 — slot 0 visibility-gate bitmap</summary>
    public const uint CLIENT_DBG_SLOT0_GATES = 0x803FCFDC;
    /// <summary>u32 — ++ every client sync tick</summary>
    public const uint CLIENT_HEARTBEAT_ADDR = 0x803FCFEC;
    /// <summary>u32 — ticks spent in unstable/hold branch</summary>
    public const uint CLIENT_DBG_UNSTABLE_HITS = 0x803FCFF0;
    /// <summary>u32 — bit0 stable, bit1 sceneChanged, bit2 linkAlive</summary>
    public const uint CLIENT_DBG_STABILITY_BITS = 0x803FCFF4;
    /// <summary>u32 — active count C# last wrote</summary>
    public const uint CLIENT_DBG_LAST_ACTIVE = 0x803FCFF8;
    /// <summary>u32 — C# header write counter</summary>
    public const uint CLIENT_DBG_WRITE_COUNTER = 0x803FCFFC;
    public const int DAPY_OFF_SPEED_F = 0x254;
    public const int DAPY_OFF_NO_RESET_FLG0 = 0x29C;
    public const int DAPY_OFF_NO_RESET_FLG1 = 0x2A0;
    public const int DAPY_OFF_MAX_NORMAL_SPEED = 0x2A8;
    /// <summary>mAnmRatioUnder[0].mRatio</summary>
    public const int DAPY_OFF_ANM_RATIO_UNDER0 = 0x2FB4;
    /// <summary>ResTIMG* mpCurrLinktex — the linktexS3TC header in the shared TEX1</summary>
    public const int DAPY_OFF_CURR_LINKTEX = 0x338;
    public const int DAPY_OFF_CUR_PROC = 0x31D8;
    public const int DAPY_OFF_STICK_DISTANCE = 0x35B0;
    public const int DAPY_OFF_VELOCITY = 0x35BC;
    public const int DAPY_OFF_MODE_FLG = 0x3618;
    /// <summary>u16 mEquipItem</summary>
    public const int DAPY_OFF_EQUIP_ITEM = 0x3560;
    /// <summary>s16 m34E8 — stick direction + camera (what ATN_MOVE blends on)</summary>
    public const int DAPY_OFF_STICK_ANGLE = 0x34E8;
    /// <summary>u16 — m_anm_heap_upper[UPPER_MOVE2].mIdx; guard/REST anims below</summary>
    public const int DAPY_OFF_UPPER_ANM_IDX = 0x301C;
    /// <summary>f32 — mFrameCtrlUnder[0].mFrame; goes backwards on a proc restart</summary>
    public const int DAPY_OFF_UNDER_FRAME = 0x303C;
    /// <summary>u8  — m34C4 combo step (changeCutProc ++)</summary>
    public const int DAPY_OFF_CUT_COMBO = 0x34C4;
    /// <summary>u16 — m3562: item held once the REST (draw/sheathe) anim finishes</summary>
    public const int DAPY_OFF_NEXT_EQUIP_ITEM = 0x3562;
    /// <summary>draw/sheathe upper anim</summary>
    public const int DAPY_UPPER_ANM_REST = 0xD7;
    public const int DAPY_PROC_GUARD_0 = 0x0C;
    public const int DAPY_PROC_GUARD_1 = 0x0D;
    public const int DAPY_PROC_GUARD_2 = 0x6D;
    public const int DAPY_UPPER_ANM_GUARD_0 = 0x16;
    public const int DAPY_UPPER_ANM_GUARD_1 = 0x1B;
}
